// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDtTzprWny5_SJ1IIKFU_mfPVpRU-dQfTg',
    appId: '1:44058728431:web:b792effba03a7bb939081a',
    messagingSenderId: '44058728431',
    projectId: 'projeto-flutter-2024',
    authDomain: 'projeto-flutter-2024.firebaseapp.com',
    storageBucket: 'projeto-flutter-2024.appspot.com',
    measurementId: 'G-THJMQJC5Z3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUZW3XiHGABFI-XjxOCkGboH9AWm0CypY',
    appId: '1:44058728431:android:6d94cc369f575e4b39081a',
    messagingSenderId: '44058728431',
    projectId: 'projeto-flutter-2024',
    storageBucket: 'projeto-flutter-2024.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjHJ_RZEBUrtOjCISrcw_kwxgH8I3RFis',
    appId: '1:44058728431:ios:4485b6000a9b380239081a',
    messagingSenderId: '44058728431',
    projectId: 'projeto-flutter-2024',
    storageBucket: 'projeto-flutter-2024.appspot.com',
    iosBundleId: 'com.example.projFlutter2024',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCjHJ_RZEBUrtOjCISrcw_kwxgH8I3RFis',
    appId: '1:44058728431:ios:4485b6000a9b380239081a',
    messagingSenderId: '44058728431',
    projectId: 'projeto-flutter-2024',
    storageBucket: 'projeto-flutter-2024.appspot.com',
    iosBundleId: 'com.example.projFlutter2024',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDtTzprWny5_SJ1IIKFU_mfPVpRU-dQfTg',
    appId: '1:44058728431:web:1fa5132b2d8636b839081a',
    messagingSenderId: '44058728431',
    projectId: 'projeto-flutter-2024',
    authDomain: 'projeto-flutter-2024.firebaseapp.com',
    storageBucket: 'projeto-flutter-2024.appspot.com',
    measurementId: 'G-3RR405VT46',
  );

}